In [27]:
print(1)

## Síntaxe de Python

In [28]:
lista = []
dic = {}

In [31]:
lista = ["vicente",10,14,0,9,False]
dic = {"Vicente":10,"Fialho":2,"Neto":1000}

In [32]:
print(lista[0])
print(dic["Vicente"])

vicente
10


## Importando Numpy

In [33]:
import numpy as np
np.set_printoptions(threshold=np.nan)

In [34]:
matriz_exemplo = np.matrix('1 0 0; 0 0 1; 0 1 0')

## Função auxiliar

In [36]:
def removearray(L,arr):
    ind = 0
    size = len(L)
    while ind != size and not np.array_equal(L[ind],arr):
        ind += 1
    if ind != size:
        L.pop(ind)
    else:
        raise ValueError('array not found in list.')

## Função GE

In [37]:
def ge(mi,list_of_blocks):
    
    nee = np.sum(mi)
    n1 =0
    mrxnr= 0
    for block in list_of_blocks:
        nee -= np.sum(block)
        n1 += np.sum(block)
        mrxnr += block.shape[0]*block.shape[1]

    pee = nee/np.sum(mi)
    ex = pee
    es = n1/mrxnr
    ge = ((1-ex)+(es))/2
    
    return ge

In [38]:
matriz_teste = np.matrix('1 1 0 0; 0 1 0 0; 0 0 1 1; 0 0 1 1')
print(matriz_teste)

[[1 1 0 0]
 [0 1 0 0]
 [0 0 1 1]
 [0 0 1 1]]


In [39]:
lista_blocks = [matriz_teste[0:2,0:2],matriz_teste[2:,2:]]
print(lista_blocks)

[matrix([[1, 1],
        [0, 1]]), matrix([[1, 1],
        [1, 1]])]


In [40]:
ge(matriz_teste,lista_blocks)

0.9375

## Dividir em dois blocos

In [42]:
def bk1(matrix):
    #Cria lista vazia para guardar resultados
    lista=[]
    #Itera sobre as linhas da matriz
    for i in range(matrix.shape[0]-1):
        #Itera sobre as colunas da matriz
        for j in range(matrix.shape[1]-1):
            #Guarda uma alternativa na lista
            lista.append([matrix[0:i+1,0:j+1],matrix[i+1:,j+1:]])
    #Retorna a lista final
    return lista

In [43]:
lista_blocos = bk1(matriz_teste)

In [45]:
lista_blocos

[[matrix([[1]]), matrix([[1, 0, 0],
          [0, 1, 1],
          [0, 1, 1]])], [matrix([[1, 1]]), matrix([[0, 0],
          [1, 1],
          [1, 1]])], [matrix([[1, 1, 0]]), matrix([[0],
          [1],
          [1]])], [matrix([[1],
          [0]]), matrix([[0, 1, 1],
          [0, 1, 1]])], [matrix([[1, 1],
          [0, 1]]), matrix([[1, 1],
          [1, 1]])], [matrix([[1, 1, 0],
          [0, 1, 0]]), matrix([[1],
          [1]])], [matrix([[1],
          [0],
          [0]]), matrix([[0, 1, 1]])], [matrix([[1, 1],
          [0, 1],
          [0, 0]]), matrix([[1, 1]])], [matrix([[1, 1, 0],
          [0, 1, 0],
          [0, 0, 1]]), matrix([[1]])]]

## Dividir em N+1 blocos

In [47]:
def bk2(lista,x):
    #Itera sobre a lista de alternativas
    for ind in range(len(lista)):
        #Verifica se o elemento é de comprimento x-1
        if len(lista[ind])==x-1:
            #Itera sobre os elementos dentro de uma alternativa
            for b_ind in range(len(lista[ind])):
                #Verifica se é possível dividir a alternativa em mais blocos
                if (np.shape(lista[ind][b_ind])[0]>1 and np.shape(lista[ind][b_ind])[1]>1):
                    #Copia parte da matriz que não será dividida 
                    temp = lista[ind].copy()
                    new_matrix = temp[b_ind]
                    removearray(temp,new_matrix)
                    temp2 = temp.copy()
                    #Itera sobre a parte dividível
                    for l in range(new_matrix.shape[0]-1):
                        for k in range(new_matrix.shape[1]-1):
                            #Guarda as divisões possíveis em novas 
                            temp2.append(new_matrix[0:l+1,0:k+1])
                            temp2.append(new_matrix[l+1:,k+1:])
                            lista.append(temp2)
                            temp2 = temp.copy()

In [49]:
bk2(lista_blocos,4)

len(lista_blocos)

33

In [4]:
#bk2(lista_blocos,4)
#len(lista_blocos)

In [1]:
#print(lista_blocos)

In [5]:
#lista_blocos[10]

## Função Principal

In [50]:
def main_prog(mi):
    
    lista=bk1(mi)
    for x in range(min(np.shape(mi)[0],np.shape(mi)[1])-2):
        bk2(lista,x+3)
    
    results ={}
    for i in range(len(lista)):
        results[i]=ge(mi,lista[i])
    
    final = lista[max(results,key=results.get)]
    #return lista
    return (final,ge(mi,final))

In [51]:
print(matriz_teste)

[[1 1 0 0]
 [0 1 0 0]
 [0 0 1 1]
 [0 0 1 1]]


In [52]:
main_prog(matriz_teste)

([matrix([[1, 1],
          [0, 1]]), matrix([[1, 1],
          [1, 1]])], 0.9375)

In [53]:
matriz_aleatoria = np.random.randint(2,size=(8,8))
print(matriz_aleatoria)

[[0 0 1 0 0 0 1 1]
 [1 1 0 0 1 0 1 1]
 [1 0 1 1 1 0 1 1]
 [0 1 0 0 0 0 1 0]
 [0 0 1 1 1 0 0 0]
 [0 1 1 0 0 0 0 1]
 [1 0 1 1 1 0 0 0]
 [0 1 1 0 1 0 1 0]]


In [54]:
main_prog(matriz_aleatoria)

([array([[0]]), array([[1, 0, 0, 1, 0, 1, 1],
         [0, 1, 1, 1, 0, 1, 1],
         [1, 0, 0, 0, 0, 1, 0],
         [0, 1, 1, 1, 0, 0, 0],
         [1, 1, 0, 0, 0, 0, 1],
         [0, 1, 1, 1, 0, 0, 0],
         [1, 1, 0, 1, 0, 1, 0]])], 0.64)

In [62]:
matriz_exemplo = np.matrix('1 1 0 0 0 0 0 0; 1 0 0 0 1 1 0 0; 0 0 1 1 0 0 1 0; 0 0 1 0 0 0 1 1; 0 1 0 0 1 1 0 0')

In [63]:
print(matriz_exemplo)

[[1 1 0 0 0 0 0 0]
 [1 0 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 0]
 [0 0 1 0 0 0 1 1]
 [0 1 0 0 1 1 0 0]]


In [64]:
main_prog(matriz_exemplo)

([matrix([[1, 1]]), matrix([[0, 0, 1, 1, 0, 0],
          [1, 1, 0, 0, 1, 0],
          [1, 0, 0, 0, 1, 1],
          [0, 0, 1, 1, 0, 0]])], 0.6593406593406594)